name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          for i in {1..3}; do
            echo "Attempt $i"
            curl -s https://project-angler.onrender.com/api/health && break
            sleep 10
          done
